%startDataFile


%1-sub id, 2-trial num, 3- group, 4-age, 5 cstegory -met, ins, 6-modality,
%7-reaction time, 8-error, 9-mouse distance, 10 zero vel, 11-total num aois
%visited, 12 peak vel, 13-16 ABCD AOI visits, Eye ABCD 17-20 duration,
%21-24 Eye num visits ABCD, 25-total aoi visits, 26-29 ABCD mean duration

if(~exclude_trial_list(trial))
    AOI_mouse_visits=zeros(1,5);
    
    for i=0:4
        AOI_mouse_visits(i+1)=sum(mouse_AOIs_visited(:,3)==i);
    end
    
    fprintf(fileID,['%d\t%d\t%s\t%s\t%d\t%d\t%g\t%d\t0%g\t%d\t%d\t%d\t%d\t%d\t%d\t'...
        '%g\t%g\t%g\t%g\t%g\t%d\t%d\t%d\t%d\t%d\t%d\t%g\t%g\t%g\t%g\t%g\t\n'], ...
        subjID(trial), trial, subject_summary.Group{sub_rng(trial)}, ...
        subject_summary.Age{sub_rng(trial)}, RT(trial), error(trial), ...
        mouse_distance_traveled,mouse_num_zero_crossings,...
        mouse_peakVel,mouse_num_AOIs_visited, ...
        AOI_mouse_visits, AOI_total_dur, AOI_num_visits,sum(AOI_num_visits),...
        AOI_mean_dur);
else
    
    %do nothing? ask sobh maybe write zeros instead?
    %     fprintf(fileID,['%d\t%d\t%s\t%s\t%d\t%d\t%g\t%d\t0%g\t%d\t%d\t%d\t%d\t%d\t%d\t'...
    %         '%g\t%g\t%g\t%g\t%g\t%d\t%d\t%d\t%d\t%d\t%d\t%g\t%g\t%g\t%g\t%g\t\n'], ...
    %         subjID, trial, subject_summary.Group{sub_rng}, ...
    %         subject_summary.Age{sub_rng}, RT, error, ...
    %         0,0,...
    %         0,0, ...
    %         AOI_mouse_visits, AOI_total_dur, AOI_num_visits,sum(AOI_num_visits),...
    %         AOI_mean_dur);
end
